### ISSUE TITLE
In SegmPred, only Generator framework is used?

### ISSUE THREAD

**Issue by chowkamlee81** [facebookresearch/SegmPred#1]
Thanks for sharing the code for reference. had a query listed below.

When compared to paper "Deep multi-scale video prediction beyond mean square error" where both Generator and discriminator was used for training. 
In this working code, it seems only Generator is used using Multi-scale network. I would like to know why discriminator network is not used? Kindly let us know.

**Comment by coupriec** [comment]
Hi, we reported in the paper results with adversarial training for the S2S model that were not better than with using the model without adversarial training (actually a little worst for mid-term prediction). Therefore when cleaning the code we removed this part. For RGB frame prediction (X2X models), adversarial training plays a positive role, you may use Michael Mathieu's code available on github as well (https://github.com/coupriec/VideoPredictionICLR2016)
Best,
Camille
